a = int(input("Введите первое число: "))
b = int(input("Введите второе число: "))
c = int(input("Введите второе число: "))
print(a, b, c)
print(a, b, c, sep=":")
print(f"{a} \n{b} \n{c}")
print(f"-{a} \n-{b} \n-{c}")